# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Kyhle Öhlinger

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Welcome to my blog!

description: Blog created using a dbyll Jekyll Theme
author:
  name: Kyhle Öhlinger
  email: kyhle@ohlinger.co
  github: KyhleOhlinger
  twitter: KyhleO
  linkedin: kyhleohlinger
  bio: Information Security Consultant

categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.linkedin.com/dms/C4D04AQE0tiThk5nkhg/profile-originalphoto-shrink_900_1200/0?m=AQIHUPLYMtYaqwAAAXElf6TjRHSHZxAlPpUtfoda9ByvYlQi29cwXl4XzQ&e=1585558454&v=beta&t=n4vifRtUKPspRRnCdT-S1hhbZ0-EEIsHVVydADvuHyc

BASE_PATH:

plugins:
  - jekyll-paginate
